<a href="https://colab.research.google.com/github/somilasthana/MachineLearningSkills/blob/master/NLP_Gensim_Vector_Space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Analysing Complaints Data

In [1]:
!wget https://data.consumerfinance.gov/api/views/s6ew-h6mp/rows.csv?accessType=DOWNLOAD

--2019-10-14 21:05:50--  https://data.consumerfinance.gov/api/views/s6ew-h6mp/rows.csv?accessType=DOWNLOAD
Resolving data.consumerfinance.gov (data.consumerfinance.gov)... 52.206.140.205, 52.206.140.199, 52.206.68.26
Connecting to data.consumerfinance.gov (data.consumerfinance.gov)|52.206.140.205|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/csv]
Saving to: ‘rows.csv?accessType=DOWNLOAD’

rows.csv?accessType     [        <=>         ] 809.77M  3.70MB/s    in 1m 54s  

2019-10-14 21:07:47 (7.09 MB/s) - ‘rows.csv?accessType=DOWNLOAD’ saved [849110889]



In [0]:
!mv /content/rows.csv?accessType=DOWNLOAD /content/complaints.csv

In [0]:
import pandas as pd
import numpy as np
import scipy

In [4]:
df_complaints = pd.read_csv("/content/complaints.csv")

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (5,6,11,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [5]:
df_complaints.head().T

0  ...                                                  4
Date received                                                        10/12/2019  ...                                         10/11/2019
Product                       Credit reporting, credit repair services, or o...  ...                        Credit card or prepaid card
Sub-product                                                    Credit reporting  ...         General-purpose credit card or charge card
Issue                                               Improper use of your report  ...                       Problem when making payments
Sub-issue                     Credit inquiries on your report that you don't...  ...  You never received your bill or did not know a...
Consumer complaint narrative                                                NaN  ...                                                NaN
Company public response                                                     NaN  ...                                                NaN
Company                                                            Avantus, LLC  ...                          NAVY FEDERAL CREDIT UNION
State                                                                        MS  ...                                                 FL
ZIP code                                                                  39648  ...                                              335XX
Tags                                                                        NaN  ...                                      Servicemember
Consumer consent provided?                                                  NaN  ...                                                NaN
Submitted via                                                               Web  ...                                                Web
Date sent to company                                                 10/12/2019  ...                                         10/11/2019
Company response to consumer                                        In progress  ...                                        In progress
Timely response?                                                            Yes  ...                                                Yes
Consumer disputed?                                                          NaN  ...                                                NaN
Complaint ID                                                            3403230  ...                                            3403477

[18 rows x 5 columns]

In [6]:
len(df_complaints)

1405841

In [7]:
df_complaints.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID'],
      dtype='object')

In [10]:
len(df_complaints[df_complaints['Consumer complaint narrative'].isna()])

956071

In [12]:
df_complaints['Consumer complaint narrative'].unique()[:5]

array([nan,
       'I recently did an application for an apartment in XXXX and was denied and told by the apartment that two of my credit cards with the same company was closed. I was told by the apartment that the company closed my accounts in XXXX without notice or my knowledge. I immediately called XXXX XXXX XXXX and was told that my accounts were NOT closed. I checked all 3 credit bureaus and they indeed closed and sent out information to all three bureaus stating my accounts were closed. I called again and multiple customer care agents state that the accounts were not closed but my credit line was suspended and that this was their policy. I understand but why would you send out to the bureaus that the accounts are closed when they are NOT there is a major difference. I attempted to dispute this with all three bureaus with no success. Because of how they reported it dropped my score significantly and is currently hindering me from getting approved not just for these apartments but 

In [13]:
df_complaints['Company public response'].unique()

array([nan,
       'Company believes the complaint is the result of a misunderstanding',
       'Company has responded to the consumer and the CFPB and chooses not to provide a public response',
       'Company believes it acted appropriately as authorized by contract or law',
       'Company disputes the facts presented in the complaint',
       'Company believes complaint caused principally by actions of third party outside the control or direction of the company',
       'Company believes complaint is the result of an isolated error',
       "Company can't verify or dispute the facts in the complaint",
       'Company believes complaint represents an opportunity for improvement to better serve consumers',
       'Company believes complaint relates to a discontinued policy or procedure',
       'Company chooses not to provide a public response'], dtype=object)

In [15]:
df_complaints['Product'].value_counts()

Credit reporting, credit repair services, or other personal consumer reports    288216
Mortgage                                                                        288037
Debt collection                                                                 265422
Credit reporting                                                                140432
Credit card                                                                      89190
Bank account or service                                                          86206
Credit card or prepaid card                                                      58890
Student loan                                                                     54415
Checking or savings account                                                      50453
Consumer Loan                                                                    31604
Vehicle loan or lease                                                            13799
Money transfer, virtual currency, or money 

In [16]:
df_complaints['Sub-product'].value_counts()

Credit reporting                              282904
Checking account                               96939
Other mortgage                                 86635
Conventional fixed mortgage                    70613
I do not know                                  54534
General-purpose credit card or charge card     45542
Other (i.e. phone, health club, etc.)          44544
Other debt                                     36072
Conventional home mortgage                     35026
FHA mortgage                                   33098
Credit card                                    28698
Conventional adjustable mortgage (ARM)         25380
Non-federal student loan                       25164
Credit card debt                               25121
Federal student loan servicing                 24280
Medical                                        21187
Medical debt                                   19435
Other bank product/service                     17825
Vehicle loan                                  

In [9]:
len(df_complaints['Sub-product'].unique())

77

In [0]:
df_credit_reporting = df_complaints[df_complaints['Product'] == 'Credit reporting']

In [6]:
df_credit_reporting['Sub-product'].unique()

array([nan], dtype=object)

In [50]:
df_credit_reporting['Consumer complaint narrative'].unique()[:5]

array([nan,
       "At the beginning of  XXXX  I started receiving letter from  Midlabd  funding saying I owe money on my   XXXX   XXXX   account from  XXXX  ( which I closed and paid on  XXXX  ) I called them after they kept sending me the same offer Over again.  Midland  funding sent me a letter recently saying that my case was close and account was closed I did n't not owe anything. They said   XXXX   XXXX   sold this account to them and after the disputed it showed I did n't owe anything. But I see it was reported to my credit report. How can I get that removed?",
       'A tax lien was issued in   XXXX   while I was  XXXX  years ago with the state of Georgia. I was stationed in California but will still paying Georgia taxes and was away on  XXXX . It was handled upon my return via certified mail with payment. It was stamped released and I was told that it would be removed from my credit report. However, it is still being reported by the Credit Bureaus. I have attached a screenshot

In [7]:
df_credit_reporting.dropna(subset=['Consumer complaint narrative'], inplace=True)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [8]:
df_credit_reporting['Consumer complaint narrative'] = df_credit_reporting['Consumer complaint narrative'].apply(lambda x: str(x).replace('XXXX', ''))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [9]:
df_credit_reporting['Consumer complaint narrative'].unique()[:5]

array(["At the beginning of    I started receiving letter from  Midlabd  funding saying I owe money on my         account from    ( which I closed and paid on    ) I called them after they kept sending me the same offer Over again.  Midland  funding sent me a letter recently saying that my case was close and account was closed I did n't not owe anything. They said         sold this account to them and after the disputed it showed I did n't owe anything. But I see it was reported to my credit report. How can I get that removed?",
       'I HAVE DISPUTED WITH EQUIFAX ABOUT INQUIRES ON MY CREDIT REPORT THAT I DO NOT RECOGNIZE THEY STATED THAT THEY HAVE INVESTIGATED MY INQUIRES BUT I KNOW THEY HAVE NOT THEY WILL NOT SEND VALIDATION FOR THE INQUIRES I KNOW THAT THE INQUIRES DO NOT HAVE NUMBERS THAT ARE WORKING THE INQUIRES ARE AS FO LLOWS 1-      ,           -        ,         ,        ,            ,            ,        ',
       'You removed             because the company could not provid

In [0]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [0]:
all_doc = nlp(df_credit_reporting.iloc[1]["Consumer complaint narrative"])

In [0]:
df_credit_reporting_sample = df_credit_reporting.sample(frac=0.2)

In [0]:
def token_func(all_doc):
  rec = []
  for token in all_doc:
    if token.is_stop:
      continue
    if token.is_punct:
      continue
    if token.is_space:
      continue
    rec.append(token.text.strip().lower())
  return rec

In [0]:
df_credit_reporting_sample['SpacyObject'] = df_credit_reporting_sample['Consumer complaint narrative'].apply(lambda x: nlp(x))

In [0]:
df_credit_reporting_sample['Tokens'] = df_credit_reporting_sample['SpacyObject'].apply(lambda x: token_func(x))

In [25]:
df_credit_reporting_sample["Tokens"].head()

919262    [account, showing, updated, balance, need, pay...
981661    [account, charged, sold, debt, collection, age...
668604    [went, buy, car, dealer, called, authroized, p...
781809    [disputed, items, equifax, credit, report, cer...
728498    [submitted, letter, equifax, stating, informat...
Name: Tokens, dtype: object

In [0]:
import gensim

In [0]:
def combine_func(row):
  text = " ".join(row)
  return text

df_credit_reporting_sample["GensimInput"] = df_credit_reporting_sample["Tokens"].apply(lambda x: combine_func(x))

In [30]:
df_credit_reporting_sample["GensimInput"].head()

919262    account showing updated balance need payments ...
981661    account charged sold debt collection agency pa...
668604    went buy car dealer called authroized pull cre...
781809    disputed items equifax credit report certified...
728498    submitted letter equifax stating information f...
Name: GensimInput, dtype: object

In [0]:
documents = [ gensim.utils.simple_preprocess(text) for text in df_credit_reporting_sample["GensimInput"]]

In [0]:
model = gensim.models.Word2Vec (documents, size=150, window=10, min_count=2, workers=10)

In [33]:
model.train(documents,total_examples=len(documents),epochs=10)

(2704471, 3287650)

In [34]:
w1 = "disputed"
model.wv.most_similar (positive=w1)

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('verified', 0.5881372690200806),
 ('deleted', 0.5878233909606934),
 ('disputing', 0.569312572479248),
 ('interesting', 0.524124264717102),
 ('unverified', 0.515620231628418),
 ('continues', 0.5094890594482422),
 ('numerous', 0.4953485429286957),
 ('validated', 0.4950898587703705),
 ('inserted', 0.4865126609802246),
 ('remains', 0.4821174740791321)]